export class CompanyEntity {
  id: string;
  name: string;
  date: string;
  address: string;
  socialReason: string;
  SEC_ACT: string;
  CA_LAST: number;
  CA_PREVISIONNEL: number;
  CA_A_VENIR: number;
  MARGE_BRUTE_EXPL: number;
  NBRE_EMPL: number;
  DATA_NBRE_PERS: string;
  SAUVEGARDES_REG: boolean;
  ANTIVIRUS_FIREWALL: boolean;
  MISES_A_JOUR: boolean;
  ANALYSE_VULNERABILITES: boolean;
  LEAST_PRIVILEGE: boolean;
  CONTROLE_ACCES: boolean;
  CHARTE_MOT_DE_PASSE: boolean;
  DONNEES_CRYPTEES: boolean;
  STANDARD_PCI_DSS: boolean;
  VERIF_SECU_PRESTATAIRES: boolean;
  AUDIT_ANNUEL_PRESTATAIRES: boolean;
  POLITIQUE_REF_SECU: boolean;
  PLAN_CONTINUITE: boolean;
  RTO_RPO_DEFINIS: boolean;
  FORMATION_EMPLOYES: boolean;
  VICTIME_SINISTRE: boolean;
  OBJET_ENQUETES: boolean;
  DEJA_ETE_ASSURE: boolean;
  MAJ_GARANTIE_AUG: boolean;
  MAJ_GARANTIE_DIM: boolean;
  NBRE_RECLAMATIONS: number;
  R_SOLVABILITE: number;
  TAUX_COUVERTURE_DETTE: number;

  constructor(company: CompanyEntity) {
    this.id = company.id;
    this.name = company.name;
    this.date = company.date;
    this.address = company.address;
    this.socialReason = company.socialReason;
    this.SEC_ACT = company.SEC_ACT;
    this.CA_LAST = company.CA_LAST;
    this.CA_PREVISIONNEL = company.CA_PREVISIONNEL;
    this.CA_A_VENIR = company.CA_A_VENIR;
    this.MARGE_BRUTE_EXPL = company.MARGE_BRUTE_EXPL;
    this.NBRE_EMPL = company.NBRE_EMPL;
    this.DATA_NBRE_PERS = company.DATA_NBRE_PERS;
    this.SAUVEGARDES_REG = company.SAUVEGARDES_REG;
    this.ANTIVIRUS_FIREWALL = company.ANALYSE_VULNERABILITES;
    this.MISES_A_JOUR = company.MISES_A_JOUR;
    this.ANALYSE_VULNERABILITES = company.ANALYSE_VULNERABILITES;
    this.LEAST_PRIVILEGE = company.LEAST_PRIVILEGE;
    this.CONTROLE_ACCES = company.CONTROLE_ACCES;
    this.CHARTE_MOT_DE_PASSE = company.CHARTE_MOT_DE_PASSE;
    this.DONNEES_CRYPTEES = company.DONNEES_CRYPTEES;
    this.STANDARD_PCI_DSS = company.STANDARD_PCI_DSS;
    this.VERIF_SECU_PRESTATAIRES = company.VERIF_SECU_PRESTATAIRES;
    this.AUDIT_ANNUEL_PRESTATAIRES = company.AUDIT_ANNUEL_PRESTATAIRES;
    this.POLITIQUE_REF_SECU = company.POLITIQUE_REF_SECU;
    this.PLAN_CONTINUITE = company.PLAN_CONTINUITE;
    this.RTO_RPO_DEFINIS = company.RTO_RPO_DEFINIS;
    this.FORMATION_EMPLOYES = company.FORMATION_EMPLOYES;
    this.VICTIME_SINISTRE = company.VICTIME_SINISTRE;
    this.OBJET_ENQUETES = company.OBJET_ENQUETES;
    this.DEJA_ETE_ASSURE = company.DEJA_ETE_ASSURE;
    this.MAJ_GARANTIE_AUG = company.MAJ_GARANTIE_AUG;
    this.MAJ_GARANTIE_DIM = company.MAJ_GARANTIE_DIM;
    this.NBRE_RECLAMATIONS = company.NBRE_RECLAMATIONS;
    this.R_SOLVABILITE = company.R_SOLVABILITE;
    this.TAUX_COUVERTURE_DETTE = company.TAUX_COUVERTURE_DETTE;
  }
}
